### ISSUE TITLE
Can you add support for DMC 4 SE .sngw cutscene files?

### ISSUE THREAD

**Issue by danteblackmetal** [LuBuCake/MTF.SoundTool#4]
In the original game, sngw files are actually ogg with the extension renamed. But this is not the case in 4 Special Edition.
And there's not a single tool anywhere that can open these files, even though there are other games in MT Frameworks 2.

[m00_100s.zip](https://github.com/user-attachments/files/16951447/m00_100s.zip)

**Comment by LuBuCake** [comment]
You can use this old tool to decrypt those files, just drag and drop the respective .sngw file into the executable: 
[sngw_decryptor.zip](https://github.com/user-attachments/files/16955166/sngw_decryptor.zip)
